dist: trusty

language: go

go:
  - 1.13
  - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "negapedia"
    token:
      secure: "jaaoMZyR8PBb6T+cuRzvFjZQdBMHOJ14ruO89rA95RQ5BfhfxOkPodTTdMLpmlFAqlplSVt70gCC/P2GAhNQJcGJtKF3Ha2HRuX4RvMRvIy92CR1JFC+6YeEmF7XxLPzA3v9bEy/tBwpSD6kxSKV4AKch8nOr3rjCPcxL8CZBd+uy9eB9aSmg6zAm/yJq/QFL/1kjhV9PUbTEc/xSk9rtRjeTRwhvqIxWnfEulrOpDvfL4N6YJjlzMkcHetBeclT4SfD2UsKBCnL94AqN2UIvLZ+wfF9ITDlVfxJtXKvHJra1LAKwnK1+UI00EflCLCDpSz5mUMx5XWmAyNbJSkTOZA2t1h0FatRbdTIekSxtAbEPKkjsyuFw44yu3UxuwUG6VjLvuI5TT+XINXrCjowWfik2Ntrqi3IZI43aMze8ZT9TEsJ/QZUjvdRyaogoCgXVSryugRu42PTi3Mp9K9wcWrluOn8VSVvEwYi/67W6T15tCQiSqv1dYzY09JBrDzJ3HogttTtgC8X1K3ko4GG8I0E6K75R5FcyHS71PAiNPgqQ1LG9vN5M0slBGkV4y5KYjEYmcFJETC0MRsjd0y1i9+k6OSetPkv6rVI/it7iKeDwzVXKt+Pge3aHhmVrDRX/j8RD0jmr6jxbxisgDTJAuEgTYtUtNENSUHf4qkPduQ="

before_script:
  - curl -fsSL "https://downloads.sourceforge.net/p7zip/p7zip_16.02_src_all.tar.bz2" -o p7zip.tar.bz2;
  - tar -xjf p7zip.tar.bz2;
  - rm p7zip.tar.bz2;
  - sudo make -C p7zip* DEST_HOME=/usr all3 install;
  - rm -fr p7zip*;


script:
  - go test -race ./... -coverprofile=coverage.out
  - sonar-scanner -Dsonar.projectKey=negapedia_wikidump -Dsonar.projectName=wikidump -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions=**/*_test.go -Dsonar.go.coverage.reportPaths=coverage.out